latin_chars = [
    "",
    "I",
    "II",
    "III",
    "IV",
    "V",
    "VI",
    "VII",
    "VIII",
    "IX",
    "X",
    "XI",
    "XII",
    "XIII",
    "XIV",
    "XV",
    "XVI",
    "XVII",
    "XVIII",
    "XIX",
    "XX",
    "XXI",
    "XXII",
    "XXIII",
    "XXIV",
    "XXV",
    "XXVI",
    "XXVII",
    "XXVIII",
    "XXIX",
    "XXX",
    "XXXI",
    "XXXII",
    "XXXIII",
    "XXXIV",
    "XXXV",
    "XXXVI",
    "XXXVII",
    "XXXVIII",
    "XXXIX",
    "XL",
    "XLI",
    "XLII",
    "XLIII",
    "XLIV",
    "XLV",
    "XLVI",
    "XLVII",
    "XLVIII",
    "XLIX",
    "L",
    "LI",
    "LII",
    "LIII",
    "LIV",
    "LV",
    "LVI",
    "LVII",
    "LVIII",
    "LIX",
    "LX",
    "LXI",
    "LXII",
    "LXIII",
    "LXIV",
    "LXV",
    "LXVI",
    "LXVII",
    "LXVIII",
    "LXIX",
    "LXX",
    "LXXI",
    "LXXII",
    "LXXIII",
    "LXXIV",
    "LXXV",
    "LXXVI",
    "LXXVII",
    "LXXVIII",
    "LXXIX",
    "LXXX",
    "LXXXI",
    "LXXXII",
    "LXXXIII",
    "LXXXIV",
    "LXXXV",
    "LXXXVI",
    "LXXXVII",
    "LXXXVIII",
    "LXXXIX",
    "XC",
    "XCI",
    "XCII",
    "XCIII",
    "XCIV",
    "XCV",
    "XCVI",
    "XCVII",
    "XCVIII",
    "XCIX",
    "C",
    "CI",
    "CII",
    "CIII",
    "CIV",
    "CV",
    "CVI",
    "CVII",
    "CVIII",
    "CIX",
    "CX",
    "CXI",
    "CXII",
    "CXIII",
    "CXIV",
    "CXV",
    "CXVI",
    "CXVII",
    "CXVIII",
    "CXIX",
    "CXX",
    "CXXI",
    "CXXII",
    "CXXIII",
    "CXXIV",
    "CXXV",
    "CXXVI",
    "CXXVII",
    "CXXVIII",
    "CXXIX",
]
latin_dict = {}
for i in range(len(latin_chars)):
    latin_dict[latin_chars[i]] = i

cipher = "LXXXIV CI CVIII CVIII XXXII CIX CI XXXII CXVI CIV CI XXXII CX XCVII CIX CI XXXII CXI CII XXXII CXVI CIV CI XXXII CIX XCVII CX XXXII CXIX CIV CXI XXXII CXIX CXIV CXI CXVI CI XXXII XXXIV LXXXII CXI CIX XCVII CX CV XXXII CV CXVI CI XXXII C CXI CIX CXVII CIX XXXIV XXXII XLIX XLVIII XLVIII XXXII CXVI CV CIX CI CXV XLVI"

idx = 0
result = []
while idx < len(cipher):
    chk = ""
    while True:
        chk += cipher[idx]
        if chk not in latin_dict:
            idx += 1
            break
        value = latin_dict[chk]
        idx += 1
        if idx == len(cipher):
            break
    result.append(value)

print(''.join([chr(c) for c in result]))
